title: MAIS Lab @ Yonsei
description: Mobile AI and Systems Lab at Yonsei University

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "#003876" # Yonsei royal blue

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
